hs_wv_model_before_WV2_EAP: "./models/S1_WV_oswCartSpec_hs_NN_model_05BeforeEAP.15_bestmodel_checkpoint.h5"
hs_wv_model_after_WV2_EAP: "./models/S1_WV_oswCartSpec_hs_NN_model_05.12_bestmodel_checkpoint.h5"